version: "3.7"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    ports:
      - 8000:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - traefikNet

  nginx1:
    image: nginx:alpine
    container_name: nginx1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx1.rule=Path(`/`)"
    ports:
      - 8081:80
    volumes:
      - $PWD/nginx/nginx1.html:/usr/share/nginx/html/index.html
    networks:
      - traefikNet
  
  nginx2:
    image: nginx:alpine
    container_name: nginx2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx2.rule=Path(`/api`)"
    ports:
      - 8082:80
    volumes:
      - $PWD/nginx/nginx2.html:/usr/share/nginx/html/api.html
      - $PWD/nginx/nginx2.conf.d:/etc/nginx/conf.d/default.conf
    networks:
      - traefikNet

networks:
  traefikNet:
    driver: bridge
